---
- name: Clone muttrc repo
  git:
    repo: "{{ muttrc_repo }}"
    dest: "{{ muttrc_path }}"

- name: Install mutt
  become: true
  dnf:
    name: mutt
    state: present

- name: Install elinks
  become: true
  dnf:
    name: elinks
    state: present
