---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Make sure user is in 'wheel' group
  user:
    name: "{{ user }}"
    groups: wheel
    append: true

- name: Allow 'wheel' group to have passwordless sudo
  become: true
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: visudo -cf %s
