---
- name: Configure Fedora
  hosts: all
  connection: local
  pre_tasks:
    - name: Update packages
      become: true
      dnf:
        name: "*"
        state: latest
  roles:
    - role: selinux
    - role: firewall
    - role: sudoers
    - role: ssh
    - role: sshd
    - role: git
    - role: github
      when: ENABLE_GITHUB
    - role: sshconfig
    - role: yubikey
    - role: gpg
    - role: pass
    - role: dotfiles
    - role: vim
    - role: ledger
    - role: mutt
    - role: flathub
    - role: chrome
    - role: gnome
    - role: development
    - role: tmux
    - role: cloud
