---
rpmfusion_free_url: https://download1.rpmfusion.org/free/fedora
rpmfusion_free_rpm: "rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
rpmfusion_free_rpm_url: "{{ rpmfusion_free_url }}/{{ rpmfusion_free_rpm }}"

virtualbox_packages:
  - VirtualBox
  - akmod-VirtualBox
  - "kernel-devel-{{ ansible_facts['kernel'] }}"

python_packages:
  - python3-virtualenv
  - python3-flake8
  - python3-isort
  - python3-ipython

docker_ce_repo: https://download.docker.com/linux/fedora/docker-ce.repo

docker_packages:
  - docker-ce
  - docker-compose

container_tools:
    - buildah
    - podman

utils:
  - jq
