---
- name: Clone dotfiles repository
  git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_path }}"
    accept_hostkey: true
    key_file: "{{ home }}/.ssh/id_rsa"

- name: Set ownerships and permissions
  file:
    path: "{{ dotfiles_path }}"
    recurse: true
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Setup dotfiles
  make:
    chdir: "{{ dotfiles_path }}"
    target: all
