---
- name: Enable Flathub repository
  become: true
  command: flatpak remote-add --if-not-exists flathub "{{ flathub_repo_url }}"

- name: Install Fractal
  become: true
  command: flatpak install --assumeyes flathub org.gnome.Fractal

- name: Install Spotify
  become: true
  command: flatpak install --assumeyes flathub com.spotify.Client

- name: Install Slack
  become: true
  command: flatpak install --assumeyes flathub com.slack.Slack
