---
- name: Install ledger and dependencies
  become: true
  dnf:
    name: "{{ ledger_pkgs }}"
    state: present

- name: Clone ledger repo
  git:
    repo: "{{ ledger_repo }}"
    dest: "{{ ledger_path }}"
    accept_hostkey: true
