---
- name: Install pass
  become: true
  dnf:
    name: pass
    state: present

- name: Clone passwords
  git:
    repo: "{{ passwords_repo }}"
    dest: "{{ passwords_path }}"
    accept_hostkey: true
