---
- name: Start and enable firewalld
  become: true
  systemd:
    name: firewalld
    enabled: true
    state: started

- name: Install python bindings for firewalld
  become: true
  dnf:
    name: python3-firewall
    state: present

- name: Enable services
  become: true
  firewalld:
    service: "{{ item }}"
    state: enabled
  with_items: "{{ permitted_services }}"
