---
- name: Install utils
  become: true
  dnf:
    name: "{{ utils }}"
    state: present

- name: Install vagrant
  become: true
  dnf:
    name: vagrant
    state: present

- name: Enable RPM Fusion Free
  become: true
  dnf:
    name: "{{ rpmfusion_free_rpm_url }}"
    state: present

- name: Install Virtualbox
  become: true
  dnf:
    name: "{{ virtualbox_packages }}"
    state: present

- name: Run akmods
  become: true
  command: akmods
  notify: restart systemd-modules-load

- name: Install Python development packages
  become: true
  dnf:
    name: "{{ python_packages }}"
    state: present

- name: Add Docker CE repo
  become: true
  get_url:
    url: "{{ docker_ce_repo }}"
    dest: /etc/yum.repos.d/

- name: Install Docker
  become: true
  dnf:
    name: "{{ docker_packages }}"
    state: present

- name: Enable Docker daemon
  become: true
  systemd:
    name: docker
    enabled: true
    state: started

- name: Install container tools
  become: true
  dnf:
    name: "{{ container_tools }}"
    state: present

- name: Install golang
  become: true
  dnf:
    name: golang
    state: present
