---
- name: Add Google's public key to RPM DB
  become: true
  rpm_key:
    key: "{{ google_signing_key_url }}"
    state: present

- name: Install Google Chrome
  become: true
  dnf:
    name: "{{ chrome_rpm_url }}"
    state: present
