---
- name: Ensure volume group is present
  become: true
  lvg:
    vg: "{{ vg_name }}"
    pvs: "{{ pvs }}"
    state: present

- name: Activate logical volume
  become: true
  lvol:
    vg: "{{ vg_name }}"
    lv: "{{ lv_name }}"
    size: 100%VG
    active: true

- name: Mount volume
  become: true
  mount:
    src: "{{ vg_path }}"
    path: "{{ mount_path }}"
    state: mounted
    fstype: ext4
