---
- name: Install vim
  become: true
  dnf:
    name: vim
    state: present

- name: Install Vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: "{{ home }}/.vim/bundle/Vundle.vim"

- name: Install plugins
  command: vim +PluginInstall +qal

- name: Install fzf
  become: true
  dnf:
    name: fzf
    state: present
