---
- name: Enable sshd
  become: true
  systemd:
    name: sshd
    enabled: true
    state: started

- name: Authorize keys
  authorized_key:
    user: "{{ user }}"
    state: present
    key: "{{ item }}"
  with_file:
    - personal.pub
    - work.pub
    - ipad.pub
    - iphone.pub
